// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: VaultMapperProtocol/vaultmapper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_VAULT               MessageType = 0
	MessageType_VAULT_PLAYER        MessageType = 1
	MessageType_VAULT_CELL          MessageType = 2
	MessageType_PLAYER_DISCONNECT   MessageType = 3
	MessageType_TOAST               MessageType = 4
	MessageType_VIEWER_CODE_REQUEST MessageType = 5
	MessageType_VIEWER_CODE         MessageType = 6
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "VAULT",
		1: "VAULT_PLAYER",
		2: "VAULT_CELL",
		3: "PLAYER_DISCONNECT",
		4: "TOAST",
		5: "VIEWER_CODE_REQUEST",
		6: "VIEWER_CODE",
	}
	MessageType_value = map[string]int32{
		"VAULT":               0,
		"VAULT_PLAYER":        1,
		"VAULT_CELL":          2,
		"PLAYER_DISCONNECT":   3,
		"TOAST":               4,
		"VIEWER_CODE_REQUEST": 5,
		"VIEWER_CODE":         6,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_VaultMapperProtocol_vaultmapper_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_VaultMapperProtocol_vaultmapper_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_VaultMapperProtocol_vaultmapper_proto_rawDescGZIP(), []int{0}
}

type CellType int32

const (
	CellType_CELLTYPE_UNKNOWN  CellType = 0
	CellType_CELLTYPE_ROOM     CellType = 1
	CellType_CELLTYPE_TUNNEL_X CellType = 2
	CellType_CELLTYPE_TUNNEL_Z CellType = 3
)

// Enum value maps for CellType.
var (
	CellType_name = map[int32]string{
		0: "CELLTYPE_UNKNOWN",
		1: "CELLTYPE_ROOM",
		2: "CELLTYPE_TUNNEL_X",
		3: "CELLTYPE_TUNNEL_Z",
	}
	CellType_value = map[string]int32{
		"CELLTYPE_UNKNOWN":  0,
		"CELLTYPE_ROOM":     1,
		"CELLTYPE_TUNNEL_X": 2,
		"CELLTYPE_TUNNEL_Z": 3,
	}
)

func (x CellType) Enum() *CellType {
	p := new(CellType)
	*p = x
	return p
}

func (x CellType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CellType) Descriptor() protoreflect.EnumDescriptor {
	return file_VaultMapperProtocol_vaultmapper_proto_enumTypes[1].Descriptor()
}

func (CellType) Type() protoreflect.EnumType {
	return &file_VaultMapperProtocol_vaultmapper_proto_enumTypes[1]
}

func (x CellType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CellType.Descriptor instead.
func (CellType) EnumDescriptor() ([]byte, []int) {
	return file_VaultMapperProtocol_vaultmapper_proto_rawDescGZIP(), []int{1}
}

type RoomType int32

const (
	RoomType_ROOMTYPE_UNKNOWN   RoomType = 0
	RoomType_ROOMTYPE_START     RoomType = 1
	RoomType_ROOMTYPE_BASIC     RoomType = 2
	RoomType_ROOMTYPE_ORE       RoomType = 3
	RoomType_ROOMTYPE_CHALLENGE RoomType = 4
	RoomType_ROOMTYPE_OMEGA     RoomType = 5
	RoomType_ROOMTYPE_RESOURCE  RoomType = 6
)

// Enum value maps for RoomType.
var (
	RoomType_name = map[int32]string{
		0: "ROOMTYPE_UNKNOWN",
		1: "ROOMTYPE_START",
		2: "ROOMTYPE_BASIC",
		3: "ROOMTYPE_ORE",
		4: "ROOMTYPE_CHALLENGE",
		5: "ROOMTYPE_OMEGA",
		6: "ROOMTYPE_RESOURCE",
	}
	RoomType_value = map[string]int32{
		"ROOMTYPE_UNKNOWN":   0,
		"ROOMTYPE_START":     1,
		"ROOMTYPE_BASIC":     2,
		"ROOMTYPE_ORE":       3,
		"ROOMTYPE_CHALLENGE": 4,
		"ROOMTYPE_OMEGA":     5,
		"ROOMTYPE_RESOURCE":  6,
	}
)

func (x RoomType) Enum() *RoomType {
	p := new(RoomType)
	*p = x
	return p
}

func (x RoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_VaultMapperProtocol_vaultmapper_proto_enumTypes[2].Descriptor()
}

func (RoomType) Type() protoreflect.EnumType {
	return &file_VaultMapperProtocol_vaultmapper_proto_enumTypes[2]
}

func (x RoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomType.Descriptor instead.
func (RoomType) EnumDescriptor() ([]byte, []int) {
	return file_VaultMapperProtocol_vaultmapper_proto_rawDescGZIP(), []int{2}
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	// ditched oneof because protoc refused to generate it properly
	Vault             *Vault             `protobuf:"bytes,2,opt,name=vault,proto3" json:"vault,omitempty"`
	VaultPlayer       *VaultPlayer       `protobuf:"bytes,3,opt,name=vaultPlayer,proto3" json:"vaultPlayer,omitempty"`
	VaultCell         *VaultCell         `protobuf:"bytes,4,opt,name=vaultCell,proto3" json:"vaultCell,omitempty"`
	PlayerDisconnect  *PlayerDisconnect  `protobuf:"bytes,5,opt,name=playerDisconnect,proto3" json:"playerDisconnect,omitempty"`
	Toast             *Toast             `protobuf:"bytes,6,opt,name=toast,proto3" json:"toast,omitempty"`
	ViewerCodeRequest *ViewerCodeRequest `protobuf:"bytes,7,opt,name=viewerCodeRequest,proto3" json:"viewerCodeRequest,omitempty"`
	ViewerCode        *ViewerCode        `protobuf:"bytes,8,opt,name=viewerCode,proto3" json:"viewerCode,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_VaultMapperProtocol_vaultmapper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_VaultMapperProtocol_vaultmapper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_VaultMapperProtocol_vaultmapper_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_VAULT
}

func (x *Message) GetVault() *Vault {
	if x != nil {
		return x.Vault
	}
	return nil
}

func (x *Message) GetVaultPlayer() *VaultPlayer {
	if x != nil {
		return x.VaultPlayer
	}
	return nil
}

func (x *Message) GetVaultCell() *VaultCell {
	if x != nil {
		return x.VaultCell
	}
	return nil
}

func (x *Message) GetPlayerDisconnect() *PlayerDisconnect {
	if x != nil {
		return x.PlayerDisconnect
	}
	return nil
}

func (x *Message) GetToast() *Toast {
	if x != nil {
		return x.Toast
	}
	return nil
}

func (x *Message) GetViewerCodeRequest() *ViewerCodeRequest {
	if x != nil {
		return x.ViewerCodeRequest
	}
	return nil
}

func (x *Message) GetViewerCode() *ViewerCode {
	if x != nil {
		return x.ViewerCode
	}
	return nil
}

type Toast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Toast) Reset() {
	*x = Toast{}
	mi := &file_VaultMapperProtocol_vaultmapper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Toast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Toast) ProtoMessage() {}

func (x *Toast) ProtoReflect() protoreflect.Message {
	mi := &file_VaultMapperProtocol_vaultmapper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Toast.ProtoReflect.Descriptor instead.
func (*Toast) Descriptor() ([]byte, []int) {
	return file_VaultMapperProtocol_vaultmapper_proto_rawDescGZIP(), []int{1}
}

func (x *Toast) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ViewerCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewerCodeRequest) Reset() {
	*x = ViewerCodeRequest{}
	mi := &file_VaultMapperProtocol_vaultmapper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewerCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewerCodeRequest) ProtoMessage() {}

func (x *ViewerCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_VaultMapperProtocol_vaultmapper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewerCodeRequest.ProtoReflect.Descriptor instead.
func (*ViewerCodeRequest) Descriptor() ([]byte, []int) {
	return file_VaultMapperProtocol_vaultmapper_proto_rawDescGZIP(), []int{2}
}

type ViewerCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewerCode) Reset() {
	*x = ViewerCode{}
	mi := &file_VaultMapperProtocol_vaultmapper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewerCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewerCode) ProtoMessage() {}

func (x *ViewerCode) ProtoReflect() protoreflect.Message {
	mi := &file_VaultMapperProtocol_vaultmapper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewerCode.ProtoReflect.Descriptor instead.
func (*ViewerCode) Descriptor() ([]byte, []int) {
	return file_VaultMapperProtocol_vaultmapper_proto_rawDescGZIP(), []int{3}
}

func (x *ViewerCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Vault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []*VaultCell           `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	Players       []*VaultPlayer         `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vault) Reset() {
	*x = Vault{}
	mi := &file_VaultMapperProtocol_vaultmapper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vault) ProtoMessage() {}

func (x *Vault) ProtoReflect() protoreflect.Message {
	mi := &file_VaultMapperProtocol_vaultmapper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vault.ProtoReflect.Descriptor instead.
func (*Vault) Descriptor() ([]byte, []int) {
	return file_VaultMapperProtocol_vaultmapper_proto_rawDescGZIP(), []int{4}
}

func (x *Vault) GetCells() []*VaultCell {
	if x != nil {
		return x.Cells
	}
	return nil
}

func (x *Vault) GetPlayers() []*VaultPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

type VaultPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"zigzag32,1,opt,name=x,proto3" json:"x,omitempty"`
	Z             int32                  `protobuf:"zigzag32,2,opt,name=z,proto3" json:"z,omitempty"`
	Uuid          string                 `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Color         *Color                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Yaw           float32                `protobuf:"fixed32,5,opt,name=yaw,proto3" json:"yaw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultPlayer) Reset() {
	*x = VaultPlayer{}
	mi := &file_VaultMapperProtocol_vaultmapper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultPlayer) ProtoMessage() {}

func (x *VaultPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_VaultMapperProtocol_vaultmapper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultPlayer.ProtoReflect.Descriptor instead.
func (*VaultPlayer) Descriptor() ([]byte, []int) {
	return file_VaultMapperProtocol_vaultmapper_proto_rawDescGZIP(), []int{5}
}

func (x *VaultPlayer) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *VaultPlayer) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *VaultPlayer) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *VaultPlayer) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *VaultPlayer) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

type Color struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             uint32                 `protobuf:"varint,1,opt,name=r,proto3" json:"r,omitempty"`
	G             uint32                 `protobuf:"varint,2,opt,name=g,proto3" json:"g,omitempty"`
	B             uint32                 `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Color) Reset() {
	*x = Color{}
	mi := &file_VaultMapperProtocol_vaultmapper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Color) ProtoMessage() {}

func (x *Color) ProtoReflect() protoreflect.Message {
	mi := &file_VaultMapperProtocol_vaultmapper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Color.ProtoReflect.Descriptor instead.
func (*Color) Descriptor() ([]byte, []int) {
	return file_VaultMapperProtocol_vaultmapper_proto_rawDescGZIP(), []int{6}
}

func (x *Color) GetR() uint32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *Color) GetG() uint32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *Color) GetB() uint32 {
	if x != nil {
		return x.B
	}
	return 0
}

type VaultCell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"zigzag32,1,opt,name=x,proto3" json:"x,omitempty"`
	Z             int32                  `protobuf:"zigzag32,2,opt,name=z,proto3" json:"z,omitempty"`
	CellType      CellType               `protobuf:"varint,3,opt,name=cellType,proto3,enum=CellType" json:"cellType,omitempty"`
	RoomType      RoomType               `protobuf:"varint,4,opt,name=roomType,proto3,enum=RoomType" json:"roomType,omitempty"`
	RoomName      string                 `protobuf:"bytes,5,opt,name=roomName,proto3" json:"roomName,omitempty"`
	Explored      bool                   `protobuf:"varint,6,opt,name=explored,proto3" json:"explored,omitempty"`
	Inscribed     bool                   `protobuf:"varint,7,opt,name=inscribed,proto3" json:"inscribed,omitempty"`
	Marked        bool                   `protobuf:"varint,8,opt,name=marked,proto3" json:"marked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultCell) Reset() {
	*x = VaultCell{}
	mi := &file_VaultMapperProtocol_vaultmapper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultCell) ProtoMessage() {}

func (x *VaultCell) ProtoReflect() protoreflect.Message {
	mi := &file_VaultMapperProtocol_vaultmapper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultCell.ProtoReflect.Descriptor instead.
func (*VaultCell) Descriptor() ([]byte, []int) {
	return file_VaultMapperProtocol_vaultmapper_proto_rawDescGZIP(), []int{7}
}

func (x *VaultCell) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *VaultCell) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *VaultCell) GetCellType() CellType {
	if x != nil {
		return x.CellType
	}
	return CellType_CELLTYPE_UNKNOWN
}

func (x *VaultCell) GetRoomType() RoomType {
	if x != nil {
		return x.RoomType
	}
	return RoomType_ROOMTYPE_UNKNOWN
}

func (x *VaultCell) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *VaultCell) GetExplored() bool {
	if x != nil {
		return x.Explored
	}
	return false
}

func (x *VaultCell) GetInscribed() bool {
	if x != nil {
		return x.Inscribed
	}
	return false
}

func (x *VaultCell) GetMarked() bool {
	if x != nil {
		return x.Marked
	}
	return false
}

type PlayerDisconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerDisconnect) Reset() {
	*x = PlayerDisconnect{}
	mi := &file_VaultMapperProtocol_vaultmapper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerDisconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDisconnect) ProtoMessage() {}

func (x *PlayerDisconnect) ProtoReflect() protoreflect.Message {
	mi := &file_VaultMapperProtocol_vaultmapper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDisconnect.ProtoReflect.Descriptor instead.
func (*PlayerDisconnect) Descriptor() ([]byte, []int) {
	return file_VaultMapperProtocol_vaultmapper_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerDisconnect) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_VaultMapperProtocol_vaultmapper_proto protoreflect.FileDescriptor

const file_VaultMapperProtocol_vaultmapper_proto_rawDesc = "" +
	"\n" +
	"%VaultMapperProtocol/vaultmapper.proto\"\xef\x02\n" +
	"\aMessage\x12 \n" +
	"\x04type\x18\x01 \x01(\x0e2\f.MessageTypeR\x04type\x12\x1c\n" +
	"\x05vault\x18\x02 \x01(\v2\x06.VaultR\x05vault\x12.\n" +
	"\vvaultPlayer\x18\x03 \x01(\v2\f.VaultPlayerR\vvaultPlayer\x12(\n" +
	"\tvaultCell\x18\x04 \x01(\v2\n" +
	".VaultCellR\tvaultCell\x12=\n" +
	"\x10playerDisconnect\x18\x05 \x01(\v2\x11.PlayerDisconnectR\x10playerDisconnect\x12\x1c\n" +
	"\x05toast\x18\x06 \x01(\v2\x06.ToastR\x05toast\x12@\n" +
	"\x11viewerCodeRequest\x18\a \x01(\v2\x12.ViewerCodeRequestR\x11viewerCodeRequest\x12+\n" +
	"\n" +
	"viewerCode\x18\b \x01(\v2\v.ViewerCodeR\n" +
	"viewerCode\"!\n" +
	"\x05Toast\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x13\n" +
	"\x11ViewerCodeRequest\" \n" +
	"\n" +
	"ViewerCode\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"Q\n" +
	"\x05Vault\x12 \n" +
	"\x05cells\x18\x01 \x03(\v2\n" +
	".VaultCellR\x05cells\x12&\n" +
	"\aplayers\x18\x02 \x03(\v2\f.VaultPlayerR\aplayers\"m\n" +
	"\vVaultPlayer\x12\f\n" +
	"\x01x\x18\x01 \x01(\x11R\x01x\x12\f\n" +
	"\x01z\x18\x02 \x01(\x11R\x01z\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\x12\x1c\n" +
	"\x05color\x18\x04 \x01(\v2\x06.ColorR\x05color\x12\x10\n" +
	"\x03yaw\x18\x05 \x01(\x02R\x03yaw\"1\n" +
	"\x05Color\x12\f\n" +
	"\x01r\x18\x01 \x01(\rR\x01r\x12\f\n" +
	"\x01g\x18\x02 \x01(\rR\x01g\x12\f\n" +
	"\x01b\x18\x03 \x01(\rR\x01b\"\xe3\x01\n" +
	"\tVaultCell\x12\f\n" +
	"\x01x\x18\x01 \x01(\x11R\x01x\x12\f\n" +
	"\x01z\x18\x02 \x01(\x11R\x01z\x12%\n" +
	"\bcellType\x18\x03 \x01(\x0e2\t.CellTypeR\bcellType\x12%\n" +
	"\broomType\x18\x04 \x01(\x0e2\t.RoomTypeR\broomType\x12\x1a\n" +
	"\broomName\x18\x05 \x01(\tR\broomName\x12\x1a\n" +
	"\bexplored\x18\x06 \x01(\bR\bexplored\x12\x1c\n" +
	"\tinscribed\x18\a \x01(\bR\tinscribed\x12\x16\n" +
	"\x06marked\x18\b \x01(\bR\x06marked\"&\n" +
	"\x10PlayerDisconnect\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid*\x86\x01\n" +
	"\vMessageType\x12\t\n" +
	"\x05VAULT\x10\x00\x12\x10\n" +
	"\fVAULT_PLAYER\x10\x01\x12\x0e\n" +
	"\n" +
	"VAULT_CELL\x10\x02\x12\x15\n" +
	"\x11PLAYER_DISCONNECT\x10\x03\x12\t\n" +
	"\x05TOAST\x10\x04\x12\x17\n" +
	"\x13VIEWER_CODE_REQUEST\x10\x05\x12\x0f\n" +
	"\vVIEWER_CODE\x10\x06*a\n" +
	"\bCellType\x12\x14\n" +
	"\x10CELLTYPE_UNKNOWN\x10\x00\x12\x11\n" +
	"\rCELLTYPE_ROOM\x10\x01\x12\x15\n" +
	"\x11CELLTYPE_TUNNEL_X\x10\x02\x12\x15\n" +
	"\x11CELLTYPE_TUNNEL_Z\x10\x03*\x9d\x01\n" +
	"\bRoomType\x12\x14\n" +
	"\x10ROOMTYPE_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eROOMTYPE_START\x10\x01\x12\x12\n" +
	"\x0eROOMTYPE_BASIC\x10\x02\x12\x10\n" +
	"\fROOMTYPE_ORE\x10\x03\x12\x16\n" +
	"\x12ROOMTYPE_CHALLENGE\x10\x04\x12\x12\n" +
	"\x0eROOMTYPE_OMEGA\x10\x05\x12\x15\n" +
	"\x11ROOMTYPE_RESOURCE\x10\x06BA\n" +
	"#com.nodiumhosting.vaultmapper.protoB\x10VaultMapperProtoP\x01Z\x06/protob\x06proto3"

var (
	file_VaultMapperProtocol_vaultmapper_proto_rawDescOnce sync.Once
	file_VaultMapperProtocol_vaultmapper_proto_rawDescData []byte
)

func file_VaultMapperProtocol_vaultmapper_proto_rawDescGZIP() []byte {
	file_VaultMapperProtocol_vaultmapper_proto_rawDescOnce.Do(func() {
		file_VaultMapperProtocol_vaultmapper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_VaultMapperProtocol_vaultmapper_proto_rawDesc), len(file_VaultMapperProtocol_vaultmapper_proto_rawDesc)))
	})
	return file_VaultMapperProtocol_vaultmapper_proto_rawDescData
}

var file_VaultMapperProtocol_vaultmapper_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_VaultMapperProtocol_vaultmapper_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_VaultMapperProtocol_vaultmapper_proto_goTypes = []any{
	(MessageType)(0),          // 0: MessageType
	(CellType)(0),             // 1: CellType
	(RoomType)(0),             // 2: RoomType
	(*Message)(nil),           // 3: Message
	(*Toast)(nil),             // 4: Toast
	(*ViewerCodeRequest)(nil), // 5: ViewerCodeRequest
	(*ViewerCode)(nil),        // 6: ViewerCode
	(*Vault)(nil),             // 7: Vault
	(*VaultPlayer)(nil),       // 8: VaultPlayer
	(*Color)(nil),             // 9: Color
	(*VaultCell)(nil),         // 10: VaultCell
	(*PlayerDisconnect)(nil),  // 11: PlayerDisconnect
}
var file_VaultMapperProtocol_vaultmapper_proto_depIdxs = []int32{
	0,  // 0: Message.type:type_name -> MessageType
	7,  // 1: Message.vault:type_name -> Vault
	8,  // 2: Message.vaultPlayer:type_name -> VaultPlayer
	10, // 3: Message.vaultCell:type_name -> VaultCell
	11, // 4: Message.playerDisconnect:type_name -> PlayerDisconnect
	4,  // 5: Message.toast:type_name -> Toast
	5,  // 6: Message.viewerCodeRequest:type_name -> ViewerCodeRequest
	6,  // 7: Message.viewerCode:type_name -> ViewerCode
	10, // 8: Vault.cells:type_name -> VaultCell
	8,  // 9: Vault.players:type_name -> VaultPlayer
	9,  // 10: VaultPlayer.color:type_name -> Color
	1,  // 11: VaultCell.cellType:type_name -> CellType
	2,  // 12: VaultCell.roomType:type_name -> RoomType
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_VaultMapperProtocol_vaultmapper_proto_init() }
func file_VaultMapperProtocol_vaultmapper_proto_init() {
	if File_VaultMapperProtocol_vaultmapper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_VaultMapperProtocol_vaultmapper_proto_rawDesc), len(file_VaultMapperProtocol_vaultmapper_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_VaultMapperProtocol_vaultmapper_proto_goTypes,
		DependencyIndexes: file_VaultMapperProtocol_vaultmapper_proto_depIdxs,
		EnumInfos:         file_VaultMapperProtocol_vaultmapper_proto_enumTypes,
		MessageInfos:      file_VaultMapperProtocol_vaultmapper_proto_msgTypes,
	}.Build()
	File_VaultMapperProtocol_vaultmapper_proto = out.File
	file_VaultMapperProtocol_vaultmapper_proto_goTypes = nil
	file_VaultMapperProtocol_vaultmapper_proto_depIdxs = nil
}
